Soccer API (MVP) #2
saravpereira/FieldsAndGoals-server pull request #9
Opened 2023-09-07 14:24 UTC by nghiapham1026

- Get all matches results from 1 day prior to today at /getPastResults:
- Return and save the name of teams
- Return and save dates of games
- Return and save the logos of each team
- Return and save the score of matches
- Post match data into database at the "sampleMatchData" collection through the postData() function to the /api/todo endpoint
- Define a new data schema for storage in the database. This structure contains an array of matches with their properties
![266165521-3ed71dd2-d92e-46fa-be33-2a0e379fd6e7](https://github.com/saravpereira/FieldsAndGoals-server/assets/87776690/c047375c-5065-400e-ab62-f3e8798c1ef1)
![266165776-25f54996-ec88-4d3c-9119-b2154fee807c](https://github.com/saravpereira/FieldsAndGoals-server/assets/87776690/0f9d1709-7519-4749-8670-011df0314b99)
![Screenshot Capture - 2023-09-06 - 16-51-33](https://github.com/saravpereira/FieldsAndGoals-server/assets/87776690/102c759c-8bc9-43ca-be8e-bcd129e3f35e)

2023-09-07 15:07 UTC, saravpereira commented on controllers/todo.js
> +};
do not reuse todo, create your own controller with the correct variable and file name

2023-09-07 15:09 UTC, saravpereira commented on controllers/webscrapeController.js
> +async function scrapeEspn(startDate, endDate, req, res) {
req is not used here, why are you adding it back to the argument?

2023-09-07 15:10 UTC, saravpereira commented on index.js
> +    scrapeController.scrapeEspn(startDate, endDate, req, res);
remove req if not used

2023-09-07 15:12 UTC, saravpereira commented on models/todo.js
> +module.exports = mongoose.model("Todo", todoSchema);
do not reuse todo, create your own models with the correct variable and file name

2023-09-07 15:19 UTC, saravpereira commented on utils/postData.js
> +    console.log(`Data sent to ${endpoint}:`, response.data);
api calls are not util functions. place this in the correct location

2023-09-07 15:22 UTC, saravpereira commented on controllers/constants.js
> +const serverUrl = 'http://localhost:8080';
server url should not be placed in const, add it as a variable in .env file

2023-09-07 15:23 UTC, saravpereira commented on utils/postData.js
> +    console.log(`Data sent to ${endpoint}:`, response.data);
do not call another api responsible for handling the db entry. handle it in the api you are creating

2023-09-07 15:24 UTC, saravpereira commented on controllers/constants.js
> +const serverUrl = 'http://localhost:8080';
based on my comment below, this serverUrl isnt even needed

2023-09-08 03:21 UTC, saravpereira commented on routes/postData.js
> +const Todo = require('../models/match');
this is not a todo list

2023-09-08 03:22 UTC, saravpereira commented on routes/postData.js
> +};
this is a controller, not a route.
Move this file to controller folder and rename file to updateMatchData

2023-09-08 03:23 UTC, saravpereira commented on models/todo.js
these todo stuff was here as sample reference, do not delete. please bring back all the todo changes you removed

2023-09-08 03:32 UTC, saravpereira requested changes
Architecturally, you may need to look into API routes. It use to be there for todo but you removed it all. look at for example: 
https://javascript.plainenglish.io/nodejs-backend-in-2022-setting-up-server-in-5-simple-steps-19074ab861f1

2023-09-08 04:49 UTC, nghiapham1026 commented
> Architecturally, you may need to look into API routes. It use to be there for todo but you removed it all. look at for example: https://javascript.plainenglish.io/nodejs-backend-in-2022-setting-up-server-in-5-simple-steps-19074ab861f1

The link is behind a paywall by the way.

2023-09-08 06:53 UTC, saravpereira commented on controllers/match.js
> +    const postSuccess = await postData(allMatchData);
put whatever you wrote in postData here instead of separating it into different files

2023-09-08 16:10 UTC, saravpereira commented on models/match.js
> +  { collection: "sampleMatchData"}
sample match data is not a meaningful name. Rename this to matchData

2023-09-08 16:15 UTC, saravpereira commented on models/match.js
> +  { collection: "sampleMatchData"}
when you change the name, delete sampleMatchData from the db.
**do not delete anything else**

2023-09-08 16:20 UTC, saravpereira commented on models/match.js
> +  { collection: "MatchData" }
camelCase please

2023-09-08 16:26 UTC, saravpereira approved these changes

2023-09-08 16:26 UTC, merged